### ISSUE TITLE
Always fail to render tree: "Bad argument"

### ISSUE THREAD

**Issue by phrohdoh** [itn3000/cs2dots#6]
dotnet version: `1.0.0-preview2-003148`
graphviz version: `2.38.0_1`
VSCode version: 9e4e44c19e393803e2b05fe2323cf4ed7e36880e (1.6.1)

I have verified that my `cssyntaxvisualizer.dotsPath` is set and that the value is correct.

``` json
{
    "cssyntaxvisualizer.dotsPath": "/usr/local/Cellar/graphviz/2.38.0_1/bin/dot"
}
```

![screen shot 2016-10-23 at 9 08 09 pm](https://cloud.githubusercontent.com/assets/4861023/19631679/e65e2334-9964-11e6-9f47-75cb3e3c29c3.png)

![screen shot 2016-10-23 at 9 08 17 pm](https://cloud.githubusercontent.com/assets/4861023/19631678/e65e0660-9964-11e6-9250-2095485981d4.png)

Output from `/usr/local/Cellar/graphviz/2.38.0_1/bin/dot -?` (just to prove that `dot` is valid):

```
Usage: dot [-Vv?] [-(GNE)name=val] [-(KTlso)<val>] <dot files>
(additional options for neato)    [-x] [-n<v>]
(additional options for fdp)      [-L(gO)] [-L(nUCT)<val>]
(additional options for memtest)  [-m<v>]
(additional options for config)  [-cv]

 -V          - Print version and exit
 -v          - Enable verbose mode 
 -Gname=val  - Set graph attribute 'name' to 'val'
 -Nname=val  - Set node attribute 'name' to 'val'
 -Ename=val  - Set edge attribute 'name' to 'val'
 -Tv         - Set output format to 'v'
 -Kv         - Set layout engine to 'v' (overrides default based on command name)
 -lv         - Use external library 'v'
 -ofile      - Write output to 'file'
 -O          - Automatically generate an output filename based on the input filename with a .'format' appended. (Causes all -ofile options to be ignored.) 
 -P          - Internally generate a graph of the current plugins. 
 -q[l]       - Set level of message suppression (=1)
 -s[v]       - Scale input by 'v' (=72)
 -y          - Invert y coordinate in output

 -n[v]       - No layout mode 'v' (=1)
 -x          - Reduce graph

 -Lg         - Don't use grid
 -LO         - Use old attractive force
 -Ln<i>      - Set number of iterations to i
 -LU<i>      - Set unscaled factor to i
 -LC<v>      - Set overlap expansion factor to v
 -LT[*]<v>   - Set temperature (temperature factor) to v

 -m          - Memory test (Observe no growth with top. Kill when done.)
 -m[v]       - Memory test - v iterations.

 -c          - Configure plugins (Writes $prefix/lib/graphviz/config 
               with available plugin information.  Needs write privilege.)
 -?          - Print usage and exit
```

**Comment by itn3000** [comment]
thank you for your reporting, I will investigate about it.

**Comment by itn3000** [comment]
@Phrohdoh
hmm, I cannot repro the issue.
please test the attached vsix by following steps
1. download attached vsix
2. boot vscode process
3. open command pallet and input "vsix" then enter
4. select downloaded vsix
5. reboot vscode
6. execute visualize
7. open output window and select 'CsSyntaxVisualizer' channel

and please tell me the output(screen shot may be preferrable)

**Comment by phrohdoh** [comment]
> please test the attached vsix by following steps

There is no attached file.

**Comment by phrohdoh** [comment]
Interestingly enough this works just fine for me now.
I am not sure what changed but something is correct now, thanks!

**Comment by itn3000** [comment]
OK, I'm glad to solve the problem
